apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codeclarity-ingress
  namespace: codeclarity
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: codeclarity.example.com
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 80
          - path: /repos
            pathType: Prefix
            backend:
              service:
                name: repo-service
                port:
                  number: 80
          - path: /reviews
            pathType: Prefix
            backend:
              service:
                name: review-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
